### PR TITLE
Setup deployment to Github Package Registry for nupkg artifact examples

### PR DESCRIPTION
**Pull request by j4ckofalltrades**
Refs strongbox/strongbox#1927

Deploys `nupkg` artifacts generated by `nuget-chocolatey` and `nuget-mono` examples. I got it to work using the [actions/setup-dotnet@v1](https://github.com/actions/setup-dotnet).

Sample artifacts:

- [nuget-chocolatey nupkg artifact](https://github.com/j4ckofalltrades/strongbox-examples/packages/471725)
- [nuget-mono nupkg artifact](https://github.com/j4ckofalltrades/strongbox-examples/packages/471606)

I also tried using the `strongboxci` docker images for both but ran into issues:

- [nuget-chocolatey using Docker image](https://github.com/j4ckofalltrades/strongbox-examples/blob/issue-1927/nuget-chocolatey/.github/workflows/gh-registry.yml)
- [nuget-chocolatey logs](https://github.com/j4ckofalltrades/strongbox-examples/runs/1302386028?check_suite_focus=true)
- [nuget-mono using Docker image](https://github.com/j4ckofalltrades/strongbox-examples/blob/issue-1927/nuget-mono/.github/workflows/gh-registry.yml)
- [nuget-mono logs](https://github.com/j4ckofalltrades/strongbox-examples/runs/1302382832?check_suite_focus=true)

### CODE REVIEW

**Comment by j4ckofalltrades** [comment]
@carlspring Requesting review

**Review by carlspring — APPROVED** [review]
LGTM! Thank you very much!

**Comment by carlspring** [comment]
I think we need to update something in the scripts in order to fix [this](https://github.com/j4ckofalltrades/strongbox-examples/packages/471725):
image

Any idea what we're missing?

Also, any idea why the asset for both is called `package.nupkg`?
image

**Comment by j4ckofalltrades** [comment]
> Any idea what we're missing?

The `description` tag for the `.nuspec` file in the `hello-chocolatey` example had placeholder values, along with some other metadata. I've updated them and added a link to the [.nuspec File Reference docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec)

> Also, any idea why the asset for both is called package.nupkg?

Hmm not sure if this a `nuget` or GitHub Package Registry thing. From what I can see in the logs, nuget doesn't seem to be renaming the artifact:

```
Pushing hello-chocolatey.1.0.0.nupkg to 'https://nuget.pkg.github.com/strongbox'...
PUT https://nuget.pkg.github.com/strongbox/
```

**Comment by carlspring** [comment]
Thanks for fixing the placeholders! :)
This looks good to me now.

**Comment by carlspring** [comment]
Could you please rebase this, so we can merge it? Thanks! ;)

**Comment by j4ckofalltrades** [comment]
@carlspring Merge conflicts resolved

**Pull request merged**
