### PR TITLE
Maven Hello World credentials changed

### PR DESCRIPTION
**Pull request by anki2189**
Older username is not working so changing it to newer one

### CODE REVIEW

**Comment by anki2189** [comment]
cc : @strongbox/oss-developers

**Comment by anki2189** [comment]
cc : @strongbox/core-developers

**Comment by steve-todorov** [comment]
Isn't there a `deployer` user now?

**Comment by anki2189** [comment]
> Isn't there a `deployer` user now?

Yes , `deployer` user is working. Changed `admin` to `deployer`

**Comment by carlspring** [comment]
Thanks for updating the example! :)

**Pull request merged**
